# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QA - Continuous Integration / Continuous Deployment

env:
  PROJECT_NAME: angular-seed

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node_modules folder
      uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install project dependencies
      run: yarn
      if: steps.yarn-cache.outputs.cache-hit != 'true'

    - run: yarn build --prod --progress=false
      env:
        CI: true

    - name: Deploy to netlify
      uses: nwtgck/actions-netlify@v1.0
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
      with:
        publish-dir: dist/${{ env.PROJECT_NAME }}
        production-branch: master
