# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node_modules folder
      uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-

    - name: Cache .jest folder
      uses: actions/cache@v1
      with:
        path: .jest
        key: ${{ runner.os }}-jest-cache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-jest-cache-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install project dependencies
      run: yarn
      if: steps.yarn-cache.outputs.cache-hit != 'true'

    - name: Check code format
      run: yarn format:check

    - name: Check lint code
      run: yarn lint

    - run: yarn test
    - run: yarn build --prod --progress=false
      env:
        CI: true
